### ISSUE TITLE
Doesn't work in the latest versions of Quasar

### ISSUE THREAD

**Issue by M0nik** [quasarframework/quasar-ui-qiconpicker#144]
Hello!

I am using the latest beta versions
```
quasar v2.0.0-beta.15
@quasar/cli v1.1.3
@quasar/app v3.0.0-beta.22
```
And when running the command `quasar d` get error

App • ⚠️  Extension(@quasar/qiconpicker): is not compatible with quasar v2.0.0-beta.15. Required version: ^1.5.0

What about new version support?

**Comment by hawkeye64** [comment]
@M0nik It's not been upgraded to qv2 yet

**Comment by slowaways** [comment]
> @M0nik It's not been upgraded to qv2 yet

When?

**Comment by hawkeye64** [comment]
@slowaways https://github.com/quasarframework/quasar-ui-qiconpicker/pull/158

**Comment by hawkeye64** [comment]
soon
