### ISSUE TITLE
 Need a property to say if a filter should be displayed in popup

### ISSUE THREAD

**Issue by nucle** [quasarframework/quasar-ui-qiconpicker#165]
**Is your feature request related to a problem? Please describe.**
In pop up mode we can have a lot of pages. When u search for an icon maybe u have to go through all the pages.
See attachment.

**Describe the solution you'd like**
We should add a property to say if a filter should be displayed

**Describe alternatives you've considered**
Show filter automatically when we have more then 12 pages?
But then we need a prop for disabel this behavior

**Additional context**

![image](https://user-images.githubusercontent.com/2041897/126880435-d7e98f4c-fe34-4b5f-a117-499ef1659abe.png)

**Comment by hawkeye64** [comment]
I have to look into this as I am not remembering at the moment. This should probably be in dev-land with the user when they put the picker in a QMenu. If so, then we should update the examples only instead of changing the component itself.

**Comment by hawkeye64** [comment]
Yes, up to dev-land, so closing this.
