### ISSUE TITLE
cannot find icon set when using quasar-cli vite version and quasar ext add

### ISSUE THREAD

**Issue by yachen4ever** [quasarframework/quasar-ui-qiconpicker#172]
**Describe the bug**
hi forks, first of all sorry for my english and my poor quasar & vue skills for still being self-learning. I was using quasar-cli with vite flavor and i used quasar ext add  @quasar/qiconpicker trying to get my iconpicker done. but i keeps getting errors from chrome console complaining cannot find my material-icons set.
![20220712223033](https://user-images.githubusercontent.com/9250987/178514871-e3be38b9-4ca6-4b5b-a322-55abcf9ea787.png)

i double checked my quasar.config.js and can be 100% positive that i included it in 'extras' array. After a little research, i found out the error line being import icon set.
![20220712223259](https://user-images.githubusercontent.com/9250987/178515483-a0f32374-67be-42e4-8f89-17f366f64ee2.png)

it seems being caused by vite using rollup. i found [this](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations) and the require function from qiconpicker using a path starting with a varaiable.

sorry for the bother but how could i fix it?

**Comment by hawkeye64** [comment]
This App Extension does not work with Vite yet

**Comment by OnekO** [comment]
Is there any plan to upgrade this to support Vite?
