### ISSUE TITLE
Warning when compiling

### ISSUE THREAD

**Issue by FabijanZulj11** [quasarframework/quasar-ui-qiconpicker#29]
I get this warning when compiling in dev mode.

Its installed as App Extension.

`WARNING  Compiled with 1 warnings, -- Module not found: Error: Can't resolve 'q-icon-picker/components/icon-set' in '....\presentation\node_modules@quasar\quasar-ui-qiconpicker\dist' `

**Comment by apasov** [comment]
You're duplicating #26 which is currently closed without giving any solution.

**Comment by hawkeye64** [comment]
Let's use #26
