### ISSUE TITLE
[Feature] Checkbox to view quasar interface icons in different icon sets.

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar-ui-qiconpicker#46]
It would be really nice to be able to filter the icons based on the quasar iconset - so we can compare and contrast between the different "looks" that quasar would have if you choose eva vs. fa for example.

**Comment by hawkeye64** [comment]
You mean at the same time? In the demo app?

**Comment by nothingismagick** [comment]
Not necessarily at the same time - and yeah - in the demo app. Would be helpful for discerning devs to find the right look and feel.

**Comment by hawkeye64** [comment]
ok, I get it. Will think on it. Won't be something I can do immediately as will be travelling back to C>nada soon.

**Comment by hawkeye64** [comment]
I've decided this can easily be done in dev-land by taking 2 QIconPicker components side-by-side wrapped by a parent component.
