### ISSUE TITLE
Support MDI v5 icon set from @quasar/extras

### ISSUE THREAD

**Issue by apasov** [quasarframework/quasar-ui-qiconpicker#55]
**Describe the solution you'd like**
MDI v5 was added in @quasar/extras v1.6.0
It would be nice if quasar-ui-qiconpicker could support them too.

**Comment by hawkeye64** [comment]
@apasov Yes, as soon as I am able. PRs welcomed. :)

**Comment by hawkeye64** [comment]
Fixed in v1.1.3 (soon to be released)
