### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by sylnsr** [quasarframework/quasar-ui-qiconpicker#62]
RE codepen .. I am not using my own code. I'm on your site (quasarframework.github.io) so its all your code already.

This does not seem to work on any browser on iOS. Going directly to https://quasarframework.github.io/quasar-ui-qiconpicker/examples ..
using Safari / FF / Google, does not show any icons at all.

(I wanted to see how slick this component is for iOS so went to the example page on my iPhone)

**To Reproduce**
1) On iOS 13.3.1 device (iPhone 7 Plus), using Safari / FF / Google to navigate to https://quasarframework.github.io/quasar-ui-qiconpicker/examples
2) Scroll down the examples where there should be icons.
3) None of the examples have icons

**Expected behavior**
I expect to see icons there using my iOS device

**Screenshots**
![15317B8F-C694-406D-99CC-94DC84C9EFF9](https://user-images.githubusercontent.com/4071106/81376650-3d509300-90c1-11ea-9704-16e907b794e9.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone 7 Plus
 - OS: iOS 13.3.1
 - Browser: stock browser (safari) / Google app / Firefox
 - Version: (latest of all versions)

Works fine on Silk browser (Amazon Fire Kindle) so I don't think is a mobile issue.

**Comment by hawkeye64** [comment]
@sylnsr Thanks for bringing this up! :heart:
I am seeing the same thing on my son's iPhone using Chrome browser.

Curious if this is also a MacOS/Safari issue?

I will see if it can be determined, but if anyone is set up a set up for debugging this, it'd be great if you could dive in and figure out what the issue might be. Thanks.

**Comment by hawkeye64** [comment]
@sylnsr Working on fixing this:
![image](https://user-images.githubusercontent.com/10262924/84159781-ae6dc800-aa2a-11ea-8d64-311e93c26263.png)

**Comment by hawkeye64** [comment]
Fixed in v1.2.1

**Comment by sylnsr** [comment]
Thanks!  Once I complete my project using this lib, I'll open-source it as well.

**Comment by sylnsr** [comment]
> Thanks! Once I complete my project using this lib, I'll open-source it as well.

My silly project using this excellent project is now published:
https://gitlab.com/idazco-foss/statusflags-ui

I will likely be using the Icon Picker for www.freematters.org as well.

**Comment by hawkeye64** [comment]
@sylnsr That's awesome! Thanks for letting me know!
